import {auth,db} from './firebase.js';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {collection,addDoc,deleteDoc,doc,getDoc,onSnapshot,serverTimestamp,updateDoc} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {esc,rows,newest,errorText,posterUrl,fallback,statusLabel} from './common.js';
const target=document.querySelector('#adminContent');
let editingId=null,items=[],users=[],reviews=[],stops=[],version=0,search='';
const safeTrailer=value=>{try{const url=new URL(value);return url.protocol==='https:'&&['www.youtube.com','www.youtube-nocookie.com'].includes(url.hostname)?url.href:'';}catch{return '';}};
function formMarkup(item={}){return `<form id="animeForm" class="admin-form"><div class="admin-section-title"><h2>${editingId?'Изменить тайтл':'Добавить аниме'}</h2></div><div class="admin-editor-layout"><div><div class="admin-form-grid">
<label>Название<input id="title" maxlength="160" required value="${esc(item.title)}"></label><label>Постер URL<input id="poster" type="url" value="${esc(item.poster)}" placeholder="https://..."></label>
<label>Год<input id="year" type="number" min="1900" max="2100" required value="${esc(item.year??'')}"></label><label>Статус<select id="status">${['Finished','Ongoing','Announced'].map(s=>`<option value="${s}" ${item.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></label>
<label>Эпизоды<input id="episodes" type="number" min="0" max="100000" required value="${esc(item.episodes??0)}"></label><label>Рейтинг каталога<input id="rating" type="number" min="0" max="10" step="0.1" required value="${esc(item.rating??0)}"></label>
<label>Количество оценок<input id="ratingCount" type="number" min="0" max="100000000" required value="${esc(item.ratingCount??0)}"></label><label>Жанры через запятую<input id="genres" value="${esc(Array.isArray(item.genres)?item.genres.join(', '):'')}"></label>
<label>Студия<input id="studio" maxlength="120" value="${esc(item.studio)}"></label><label>Длительность<input id="duration" maxlength="80" value="${esc(item.duration)}" placeholder="24 мин"></label>
<label>Возрастной рейтинг<input id="age" maxlength="40" value="${esc(item.age)}" placeholder="R17+"></label><label>Тип<input id="type" maxlength="40" value="${esc(item.type)}" placeholder="TV"></label>
<label>Источник<input id="source" maxlength="80" value="${esc(item.source)}" placeholder="Манга"></label><label>Трейлер YouTube<input id="trailer" type="url" value="${esc(item.trailer)}" placeholder="https://www.youtube-nocookie.com/embed/..."></label>
</div><label>Описание<textarea id="description" rows="5" maxlength="10000" required>${esc(item.description)}</textarea></label></div><aside class="poster-preview"><span>ПРЕДПРОСМОТР</span><img id="posterPreview" src="${esc(posterUrl(item.poster))}" alt="Предпросмотр постера"></aside></div>
<div class="admin-actions"><button class="button" type="submit">${editingId?'Сохранить изменения':'Добавить аниме'}</button><button id="cancelEdit" class="button secondary" type="button" ${editingId?'':'hidden'}>Отмена</button></div><p id="formMessage" class="form-message" role="status"></p></form>`;}
function mountForm(item){document.querySelector('#editor').innerHTML=formMarkup(item);const form=document.querySelector('#animeForm');form.addEventListener('submit',saveAnime);form.querySelector('#poster').addEventListener('input',event=>{document.querySelector('#posterPreview').src=posterUrl(event.target.value.trim());});document.querySelector('#cancelEdit').onclick=()=>{editingId=null;mountForm();};}
function updateStats(){const el=document.querySelector('#adminStats');if(el)el.textContent=`Тайтлов: ${items.length} · Отзывов: ${reviews.length} · Пользователей: ${users.length}`;}
function renderCatalog(){updateStats();const shown=items.filter(a=>`${a.title} ${a.year} ${a.studio||''}`.toLowerCase().includes(search));document.querySelector('#adminList').innerHTML=shown.length?shown.map(a=>`<article class="admin-item"><img class="admin-thumb" src="${esc(posterUrl(a.poster))}" alt=""><div><h3>${esc(a.title)}</h3><p>${esc(a.year)} · ⭐ ${esc(a.rating)} · ${esc(statusLabel(a.status))}</p></div><div class="admin-item-actions"><button class="button small" data-edit="${esc(a.id)}">Изменить</button><button class="button small danger" data-delete="${esc(a.id)}">Удалить</button></div></article>`).join(''):'<p class="muted">По этому запросу ничего не найдено.</p>';}
function renderUsers(){updateStats();document.querySelector('#adminUsers').innerHTML=users.length?users.map(u=>`<article class="admin-item"><div><h3>${esc(u.name||'Пользователь')}</h3><p>${esc(u.email)} · ${u.role==='admin'?'администратор':'пользователь'}</p></div><button class="button small" data-role="${esc(u.id)}" ${u.id===auth.currentUser?.uid?'disabled':''}>${u.role==='admin'?'Сделать пользователем':'Сделать администратором'}</button></article>`).join(''):'<p class="muted">Пользователей пока нет.</p>';}
function renderReviews(){updateStats();document.querySelector('#adminReviews').innerHTML=reviews.length?reviews.map(r=>`<article class="review-card"><div class="review-card-head"><strong>${esc(r.userName||'Пользователь')} · ${esc(r.animeTitle||r.animeId)}</strong><span>⭐ ${esc(r.rating)}/10</span></div><p>${esc(r.text)}</p><button class="text-button" data-review="${esc(r.id)}">Удалить отзыв</button></article>`).join(''):'<p class="muted">Отзывов пока нет.</p>';}
async function saveAnime(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type="submit"]'),message=document.querySelector('#formMessage');if(button.disabled)return;const value=id=>form.querySelector(`#${id}`).value.trim(),trailer=value('trailer');const data={title:value('title'),description:value('description'),poster:value('poster'),year:Number(value('year')),status:value('status'),episodes:Number(value('episodes')),rating:Number(value('rating')),ratingCount:Number(value('ratingCount')),genres:[...new Set(value('genres').split(',').map(s=>s.trim()).filter(Boolean))],studio:value('studio'),duration:value('duration'),age:value('age'),type:value('type'),source:value('source'),trailer:trailer?safeTrailer(trailer):''};if(!data.title||!data.description||!Number.isInteger(data.year)||data.year<1900||data.year>2100||!Number.isInteger(data.episodes)||data.episodes<0||data.episodes>100000||!Number.isFinite(data.rating)||data.rating<0||data.rating>10||!Number.isInteger(data.ratingCount)||data.ratingCount<0||data.ratingCount>100000000||data.genres.length>20||(data.poster&&posterUrl(data.poster)===fallback)||(trailer&&!data.trailer)){message.textContent='Проверьте обязательные поля, числа, URL постера и ссылку YouTube.';return;}button.disabled=true;message.textContent='Сохраняем…';try{if(editingId)await updateDoc(doc(db,'anime',editingId),data);else await addDoc(collection(db,'anime'),{...data,createdAt:serverTimestamp()});editingId=null;mountForm();document.querySelector('#formMessage').textContent='Сохранено ✓';}catch(error){console.error(error);message.textContent=errorText(error);button.disabled=false;}}
target.addEventListener('input',event=>{if(event.target.id==='adminSearch'){search=event.target.value.trim().toLowerCase();renderCatalog();}});
target.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||button.disabled)return;const notice=document.querySelector('#adminNotice');if(!notice)return;if(button.dataset.edit){editingId=button.dataset.edit;mountForm(items.find(a=>a.id===editingId));document.querySelector('#editor').scrollIntoView({behavior:'smooth'});return;}let action;if(button.dataset.delete){const item=items.find(a=>a.id===button.dataset.delete);if(!item||!confirm(`Удалить «${item.title}» из каталога?`))return;action=()=>deleteDoc(doc(db,'anime',item.id));}if(button.dataset.review){if(!confirm('Удалить этот отзыв?'))return;action=()=>deleteDoc(doc(db,'reviews',button.dataset.review));}if(button.dataset.role){const user=users.find(u=>u.id===button.dataset.role);if(!user||user.id===auth.currentUser.uid)return;const role=user.role==='admin'?'user':'admin';if(!confirm(`Изменить роль ${user.name||user.email}?`))return;action=()=>updateDoc(doc(db,'users',user.id),{role});}if(!action)return;button.disabled=true;notice.textContent='';try{await action();notice.textContent='Изменения сохранены.';if(button.dataset.delete===editingId){editingId=null;mountForm();}}catch(error){notice.textContent=errorText(error);button.disabled=false;}});
onAuthStateChanged(auth,async user=>{stops.forEach(stop=>stop());stops=[];const token=++version;if(!user){location.href='login.html';return;}try{const snap=await getDoc(doc(db,'users',user.uid));if(token!==version)return;if(snap.data()?.role!=='admin'){target.innerHTML='<section class="profile-card"><h2>Доступ запрещён</h2><p>Эта страница доступна администратору.</p></section>';return;}target.innerHTML='<p id="adminStats" class="eyebrow"></p><p id="adminNotice" role="status"></p><div id="editor"></div><section class="admin-catalog"><div class="admin-section-title"><h2>Каталог</h2><input id="adminSearch" class="admin-search" type="search" placeholder="Поиск по названию, году или студии"></div><div id="adminList" class="admin-list"></div></section><section class="admin-catalog"><h2>Модерация отзывов</h2><div id="adminReviews"></div></section><section class="admin-catalog"><h2>Пользователи и роли</h2><div id="adminUsers" class="admin-list"></div></section>';mountForm();for(const [name,id,assign,render] of [['anime','adminList',v=>{items=newest(v);},renderCatalog],['reviews','adminReviews',v=>{reviews=newest(v);},renderReviews],['users','adminUsers',v=>{users=v;},renderUsers]])stops.push(onSnapshot(collection(db,name),snapshot=>{if(token!==version)return;assign(rows(snapshot));render();},error=>{if(token!==version)return;document.querySelector(`#${id}`).innerHTML=`<p class="muted">${esc(errorText(error))}</p>`;}));}catch(error){if(token===version)target.innerHTML=`<p class="muted">${esc(errorText(error))}</p>`;}});
document.querySelector('#logoutButton')?.addEventListener('click',async()=>{try{await signOut(auth);location.href='index.html';}catch(error){document.querySelector('#adminNotice').textContent=errorText(error);}});
addEventListener('pagehide',()=>stops.forEach(stop=>stop()),{once:true});
