export const starterAnime = [
  {id:'death-note',title:'Death Note',year:2006,status:'Finished',episodes:37,genres:['Drama','Fantasy'],rating:8.6,ratingCount:1900,poster:'https://cdn.myanimelist.net/images/anime/1079/138100l.webp',studio:'Madhouse',duration:'23 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/Vt_3c8BgxV4',description:'Старшеклассник находит тетрадь, способную убить любого человека, чьё имя записано на её страницах.'},
  {id:'fullmetal-alchemist-brotherhood',title:'Fullmetal Alchemist: Brotherhood',year:2009,status:'Finished',episodes:64,genres:['Action','Adventure','Drama'],rating:9.1,ratingCount:2100,poster:'https://cdn.myanimelist.net/images/anime/1208/94745l.webp',studio:'Bones',duration:'24 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/1ac3_YdSSy0',description:'Два брата-алхимика ищут философский камень, чтобы вернуть потерянные тела и исправить роковую ошибку.'},
  {id:'demon-slayer',title:'Demon Slayer',year:2019,status:'Ongoing',episodes:63,genres:['Action','Adventure','Fantasy'],rating:8.7,ratingCount:1650,poster:'https://cdn.myanimelist.net/images/anime/1286/99889l.webp',studio:'ufotable',duration:'23 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/6vMuWuWlW4I',description:'Тандзиро становится охотником на демонов, чтобы спасти сестру и найти виновника гибели своей семьи.'},
  {id:'jujutsu-kaisen',title:'Jujutsu Kaisen',year:2020,status:'Ongoing',episodes:47,genres:['Action','Fantasy'],rating:8.6,ratingCount:1480,poster:'https://cdn.myanimelist.net/images/anime/1171/109222l.webp',studio:'MAPPA',duration:'23 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/4A_X-Dvl0ws',description:'Юдзи Итадори вступает в мир магов и проклятий после встречи с опасным древним артефактом.'},
  {id:'one-punch-man',title:'One Punch Man',year:2015,status:'Ongoing',episodes:24,genres:['Action','Comedy'],rating:8.5,ratingCount:1750,poster:'https://cdn.myanimelist.net/images/anime/12/76049l.webp',studio:'Madhouse',duration:'24 мин',age:'17+',type:'Сериал',source:'Веб-манга',trailer:'https://www.youtube-nocookie.com/embed/ExUMiF1L0HA',description:'Сильнейший герой побеждает любого противника одним ударом, но больше всего страдает от скуки.'},
  {id:'spy-x-family',title:'Spy × Family',year:2022,status:'Ongoing',episodes:37,genres:['Action','Comedy'],rating:8.4,ratingCount:980,poster:'https://cdn.myanimelist.net/images/anime/1441/122795l.webp',studio:'Wit Studio · CloverWorks',duration:'24 мин',age:'13+',type:'Сериал',source:'Манга',trailer:'',description:'Шпион, наёмная убийца и девочка-телепат изображают обычную семью ради секретной миссии.'},
  {id:'frieren',title:'Frieren: Beyond Journey’s End',year:2023,status:'Ongoing',episodes:28,genres:['Adventure','Drama','Fantasy'],rating:9.3,ratingCount:1200,poster:'https://cdn.myanimelist.net/images/anime/1015/138006l.webp',studio:'Madhouse',duration:'24 мин',age:'13+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/ZEkwCGJ3o7M',description:'Эльфийка-маг отправляется в новое путешествие, пытаясь понять людей и ценность проведённого вместе времени.'},
  {id:'vinland-saga',title:'Vinland Saga',year:2019,status:'Ongoing',episodes:48,genres:['Action','Adventure','Drama'],rating:8.8,ratingCount:1100,poster:'https://cdn.myanimelist.net/images/anime/1500/103005l.webp',studio:'Wit Studio',duration:'24 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/f8JrZ7Q_p-8',description:'Юный Торфинн взрослеет среди викингов и ищет смысл жизни за пределами мести и войны.'},
  {id:'violet-evergarden',title:'Violet Evergarden',year:2018,status:'Finished',episodes:13,genres:['Drama','Romance'],rating:8.7,ratingCount:930,poster:'https://cdn.myanimelist.net/images/anime/1795/95088l.webp',studio:'Kyoto Animation',duration:'24 мин',age:'13+',type:'Сериал',source:'Ранобэ',trailer:'',description:'Бывшая солдатка учится понимать чувства людей, записывая для них письма и узнавая значение любви.'},
  {id:'your-name',title:'Your Name',year:2016,status:'Finished',episodes:1,genres:['Drama','Romance','Fantasy'],rating:8.9,ratingCount:2200,poster:'https://cdn.myanimelist.net/images/anime/5/87048l.webp',studio:'CoMix Wave Films',duration:'1 ч 46 мин',age:'13+',type:'Фильм',source:'Оригинал',trailer:'https://www.youtube-nocookie.com/embed/3KR8_igDs1Y',description:'Двое подростков неожиданно начинают меняться телами и пытаются найти друг друга сквозь время.'},
  {id:'haikyuu',title:'Haikyu!!',year:2014,status:'Finished',episodes:85,genres:['Comedy','Drama'],rating:8.7,ratingCount:1350,poster:'https://cdn.myanimelist.net/images/anime/7/76014l.webp',studio:'Production I.G',duration:'24 мин',age:'13+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/9kLRkH9zC5k',description:'Невысокий, но невероятно упорный школьник мечтает стать выдающимся волейболистом.'},
  {id:'mob-psycho-100',title:'Mob Psycho 100',year:2016,status:'Finished',episodes:37,genres:['Action','Comedy'],rating:8.8,ratingCount:1050,poster:'https://cdn.myanimelist.net/images/anime/8/80356l.jpg',studio:'Bones',duration:'24 мин',age:'13+',type:'Сериал',source:'Веб-манга',trailer:'',description:'Скромный подросток с огромной психической силой старается жить обычной жизнью и держать эмоции под контролем.'},
  {id:'chainsaw-man',title:'Chainsaw Man',year:2022,status:'Ongoing',episodes:12,genres:['Action','Fantasy'],rating:8.5,ratingCount:1180,poster:'https://cdn.myanimelist.net/images/anime/1806/126216l.webp',studio:'MAPPA',duration:'24 мин',age:'17+',type:'Сериал',source:'Манга',trailer:'https://www.youtube-nocookie.com/embed/jk7QSGwupPA',description:'Дэндзи получает силу демона-бензопилы и начинает охоту на чудовищ в обмен на простую человеческую жизнь.'},
  {id:'steins-gate',title:'Steins;Gate',year:2011,status:'Finished',episodes:24,genres:['Drama','Fantasy'],rating:9.0,ratingCount:1600,poster:'https://cdn.myanimelist.net/images/anime/1935/127974l.webp',studio:'White Fox',duration:'24 мин',age:'13+',type:'Сериал',source:'Визуальная новелла',trailer:'https://www.youtube-nocookie.com/embed/27OZc-ku6is',description:'Группа друзей случайно создаёт способ отправлять сообщения в прошлое и сталкивается с последствиями.'},
  {id:'cowboy-bebop',title:'Cowboy Bebop',year:1998,status:'Finished',episodes:26,genres:['Action','Adventure','Drama'],rating:8.8,ratingCount:1420,poster:'https://cdn.myanimelist.net/images/anime/4/19644l.webp',studio:'Sunrise',duration:'24 мин',age:'17+',type:'Сериал',source:'Оригинал',trailer:'https://www.youtube-nocookie.com/embed/gY5nDXOtv_o',description:'Команда охотников за головами путешествует по Солнечной системе, пытаясь заработать и убежать от прошлого.'}
].map((item,index)=>({...item,createdAt:{seconds:1700000000-index*86400}}));

export const starterById = id => starterAnime.find(item=>item.id===id);
